#!/usr/bin/env ruby
require_relative 'parse'

def abs(n)
  return n < 0 ? n * -1 : n
end

def isqrt (n)
  x = n
  while (abs(x * x - n) > 0.001)
    x = (x * x + n) / (2 * x)
  end

  return x
end

# b^2 - 4ac
def calculate_discriminant(array)
  return (array[1] * array[1]) - (4 * array[0] * array[2])
end

def first_degree(array)
  return [(array[2] / array[1]) * -1.0]
end

def second_degree(array, discriminant)
  return [(-1 * array[1] + isqrt(discriminant)) / (2 * array[0]), (-1 * array[1] - isqrt(discriminant)) / (2 * array[0])]
end

def main(array)
  if array[0] == 0
    answer = first_degree(array)
  else
    discriminant =  calculate_discriminant(array)
    if discriminant < 0
      print "The discriminant is negative, there are no solutions\n"
      return
    end
    print "Discriminant is strictly positive, the two solutions are:\n"
    answer = second_degree(array, discriminant)
    if answer[0] == answer[1]
      answer.shift
    end
  end
  answer.each do |val|
    p val
  end
end

if ARGV[0] == '-v'
  $VERBOSE = true
  ARGV.shift
end

perfect_return = parse ARGV

reduced_string = perfect_return.map.with_index do |val, i|
  next if val == 0.0
  if val == val.to_i.to_f
    val = val.to_i
  end
  case i
  when 0
    "#{val}"
  when 1
    "#{val}X"
  else
    "#{val}X^#{i}"
  end
end

p perfect_return

puts "Reduced form: #{reduced_string.compact.reverse.join(' + ')} = 0"
puts "Polynomial degree: #{perfect_return.count}"

if perfect_return.count > 3
  puts "The polynomial degree is stricly greater than 2, I can't solve."
else
  perfect_return = perfect_return.reverse
  while perfect_return.count < 3
    perfect_return.unshift 0.0
  end
  p perfect_return
  main(perfect_return)
end