#!/usr/bin/env ruby
require_relative 'parse'

def abs(n)
  return n < 0 ? n * -1 : n
end

def isqrt (n)
  x = n
  while (abs(x * x - n) > 0.001)
    x = (x * x + n) / (2 * x)
  end

  return x
end

# b^2 - 4ac
def calculate_discriminant(array)
  return (array[1] * array[1]) - (4 * array[0] * array[2])
end

def first_degree(array)
  return [(array[2] / array[1]) * -1.0]
end

def second_degree(array, discriminant)
  return [(-1 * array[1] + isqrt(discriminant)) / (2 * array[0]), (-1 * array[1] - isqrt(discriminant)) / (2 * array[0])]
end

def second_degree_imaginary(array, discriminant)
  discriminant *= -1
  part1 = (-1 * array[1]) / (2 * array[0])
  part2 = (isqrt(discriminant)) / (2 * array[0])
  return [part1.to_s + " + i * " + part2.to_s, part1.to_s + " - i * " + part2.to_s]
end

def main(array)
  if (array[0] == 0 && array[1] == 0 && array[2] == 0)
    puts "All real numbers"
    return
  elsif array[0] == 0 && array[1] == 0
    puts "No real solutions"
    return
  end

  if array[0] == 0
    answer = first_degree(array)
  else
    discriminant =  calculate_discriminant(array)
    if discriminant < 0
      answer = second_degree_imaginary(array, discriminant)
      if answer[0] == answer[1]
        answer.shift
        puts "Discriminant is strictly negative, the one complex solution is:"
      else
        puts "Discriminant is strictly negative, the two complex solutions are:"
      end
    else
      answer = second_degree(array, discriminant)
      if answer[0] == answer[1]
        answer.shift
        puts "Discriminant is strictly positive, the one solution is:"
      else
        puts "Discriminant is strictly positive, the two solutions are:"
      end
    end
  end
  answer.each do |val|
    puts val
  end
end

def print_reduced(polynomial_array)
  reduced_array = polynomial_array.map.with_index do |val, i|
    next if val == 0.0
    val = val.to_i if val == val.to_i.to_f
    val = ''       if val == 1
    val = '-'       if val == -1
    case i
    when 0
      "#{val}"
    when 1
      "#{val}X"
    else
      "#{val}X^#{i}"
    end
  end.compact.reverse
  reduced_string = reduced_array.empty? ? '0' : reduced_array.join(' + ')
  puts "Reduced form: #{reduced_string} = 0"
end

def polynomial_degree(polynomial_array)
  degree = 0
  polynomial_array.each.with_index do |val, i|
    degree = i unless val == 0.0
  end
  return degree
end

if ARGV[0] == '-v'
  $VERBOSE = true
  ARGV.shift
end

p_array = parse ARGV

print_reduced p_array
degree = polynomial_degree p_array
puts "Polynomial degree: #{degree}"

if degree > 2
  puts "The polynomial degree is stricly greater than 2, I can't solve."
else
  main_array = [0.0, 0.0, 0.0]
  main_array[0] = p_array[2] unless p_array[2].nil?
  main_array[1] = p_array[1] unless p_array[1].nil?
  main_array[2] = p_array[0] unless p_array[0].nil?
  p main_array
  main(p_array)
end