#!/usr/bin/env ruby
require_relative 'parse'

perfect_return = parse ARGV

puts "Perfect Return: " + perfect_return.inspect
puts "Perfect String: #{perfect_return[0].to_s}X^0 + #{perfect_return[1].to_s}X^1 + #{perfect_return[2].to_s}X^2"
